# Generated by Django 3.2.16 on 2023-05-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='banner_title4',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_title5',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_title6',
        ),
        migrations.RemoveField(
            model_name='index',
            name='banner_title7',
        ),
    ]
