# Generated by Django 3.2.16 on 2023-05-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230508_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='banner_title4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo-Slide-1'),
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo-Slide-2'),
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo-Slide-3'),
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title7',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo-Slide-4'),
        ),
    ]
